name: Node CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          cd react-fileicons
          npm ci
          npm run build
          cd ../storybook
          npm ci
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook/storybook-static
        env:
          CI: true
